### ISSUE TITLE
Check null in checkedCopy of Solution

### ISSUE THREAD

**Issue by neokito** [hdbeukel/james-core#32]
Hi,

In this file:
https://github.com/hdbeukel/james-core/blob/master/src/main/java/org/jamesframework/core/problems/sol/Solution.java

Problem for new users:

This is a example, when the override codes are automatically generated with the IDE.

```
public class MCDPSolution extends Solution{
....
    @Override
    public Solution copy() {
        // TODO Auto-generated method stub
        return null;
    }
```

Output:
<img width="888" alt="screen shot 2016-03-22 at 10 17 27" src="https://cloud.githubusercontent.com/assets/5897215/13952707/947d2094-f016-11e5-8118-5e4270b5c8fc.png">

New minor check:

```
    @SuppressWarnings("unchecked")
    static public <T extends Solution> T checkedCopy(T solution){
        // copy solution
        Solution copy = solution.copy();
       if (copy == null)
        {
            throw new SolutionCopyException("\nDeep copy of solution of type " + solution.getClass().getSimpleName() + " failed. "
                    + "Calling copy() yields a solution with return null.\n"
                    + "- Expected cause of this type mismatch:\n"
                    + solution.getClass().getSimpleName() + " does not completly implement method copy().");
        }
        Class<?> origClass = solution.getClass();
        Class<?> copyClass = copy.getClass();
...
```

New output:
<img width="886" alt="screen shot 2016-03-22 at 10 16 21" src="https://cloud.githubusercontent.com/assets/5897215/13952660/6ffd3498-f016-11e5-9af1-5dfe6fe89ab5.png">

Regards

**Comment by hdbeukel** [comment]
Thanks for the suggestion. We will add this check.
