### ISSUE TITLE
References on delta evaluation

### ISSUE THREAD

**Issue by huanfachen** [hdbeukel/james-core#48]
Hi all. I am looking for the definition and references of delta evaluation technique in tabu search. Is there any good papers or resources that you recommend? Thanks!

**Comment by hdbeukel** [comment]
Do you mean e.g. feature-based tabu memories where moves are rejected if they affect recently modified features? If you really mean delta evaluation (i.e. the objective function) I don't see how this is related to a specific search algorithm such as tabu search.
