### ISSUE TITLE
Sharing of delta evalution / validations

### ISSUE THREAD

**Issue by ghost** [hdbeukel/james-core#49]
Using a delta evalution or delta validations, one can store relevant information of the current solution candidate to speed up the move evaluation / validation.

In my case, some part of the objective function and several constraints would need to share access to the stored information (otherwise the objective function and each participating constraint would need to compute the delta, this duplicates code and might lead to a performance issue).

Is it possible to store the information once, e.g. during the evaluation, and then to access it later from validations?

**Comment by hdbeukel** [comment]
I guess you could achieve this by defining a custom solution type and storing this shared information directly in the solution. I would compute/update this information when applying a move. It is then available for both delta evaluations and validations of future moves.

Does this solve your issue?

**Comment by ghost** [comment]
Thank you, I think that would work!
